In [1]:
import numpy as np
import pandas as pd
import re

In [10]:
dataframeu=pd.read_csv('final_users.csv')
dataframeu.head()
print(len(dataframeu))

7177

In [5]:
dataframe=dataframe.dropna(subset=['msno','city','bd','gender'])

In [6]:
print(len(dataframe))

7177

In [6]:
bd=dataframe['bd'].tolist()
bdunique=np.unique(np.array(bd))

In [7]:
city=dataframe['city'].tolist()
cityunique=np.unique(np.array(city))

In [3]:
users=dataframe['msno'].tolist()
len(users)

7177

In [12]:
dataframe=pd.read_csv('final_train.csv')
dataframe.head()
ulist = np.unique(np.array(dataframe.msno.tolist()))
dataframeu = dataframeu.loc[dataframeu['msno'].isin(ulist)]
print(len(dataframeu))
dataframeu.to_csv('final_users.csv')

5688

In [10]:
dataframe=dataframe.drop(['source_screen_name','source_type'],axis=1)
dataframe=dataframe.dropna(subset=['msno','song_id','source_system_tab'])

In [11]:
print(len(dataframe))

2548348

In [8]:
behaviours=dataframe['source_system_tab'].tolist()
behaviours=np.unique(np.array(behaviours))

In [9]:
df1=pd.read_csv('final_songs.csv')

In [10]:
df1.head()

,Unnamed: 0,Unnamed: 0.1,song_id,song_length,genre_ids,artist_name,composer,lyricist,language
0,0,1,NV9HhUzyK50tGvxb3w0PdZoaw3Ypp86XDmmMr0vgFdg=,262749,['139'],['John Legend'],['John Stephens'],['John Stephens'],52.0
1,1,2,igUq5ErBzlm2Wi05YsoiyWdxd4wbHGPaFOS8kQFhoik=,228717,['465'],['Urban Zakapa'],"['Gwon Soonil', ' Park Yongin', ' Choi JaeMan'...","['Gwon Soonil', ' Park Yongin', ' Choi JaeMan'...",31.0
2,2,3,UfK2UdQAaYF6IJUXqSJ10FsbAF3YkvMJYcTYC2Ec5m4=,222649,['1609'],['Calvin Harris'],['Calvin Harris'],['Calvin Harris'],52.0
3,3,4,nO+tjL6/qHgNO/ui0TjeP+nSsD+aoGcT9AHU7Dtrzsc=,227327,['880'],['Casting Crowns'],"['Mark Hall', 'Matt Maher', 'John Mabe', 'Blak...","['Mark Hall', 'Matt Maher', 'John Mabe', 'Blak...",52.0
4,4,5,ZxB4Y6OFY7oArWVqRWofM3g714CWrHbY4ohABjzGLFE=,256052,['1609'],['Robin Schulz'],"['Dennis Bierbrodt', ' Guido Kramer', ' Robin ...","['Dennis Bierbrodt', ' Guido Kramer', ' Robin ...",52.0

In [11]:
df1.set_index('song_id')

,Unnamed: 0,Unnamed: 0.1,song_length,genre_ids,artist_name,composer,lyricist,language
song_id,,,,,,,,
NV9HhUzyK50tGvxb3w0PdZoaw3Ypp86XDmmMr0vgFdg=,0,1,262749,['139'],['John Legend'],['John Stephens'],['John Stephens'],52.0
igUq5ErBzlm2Wi05YsoiyWdxd4wbHGPaFOS8kQFhoik=,1,2,228717,['465'],['Urban Zakapa'],"['Gwon Soonil', ' Park Yongin', ' Choi JaeMan'...","['Gwon Soonil', ' Park Yongin', ' Choi JaeMan'...",31.0
UfK2UdQAaYF6IJUXqSJ10FsbAF3YkvMJYcTYC2Ec5m4=,2,3,222649,['1609'],['Calvin Harris'],['Calvin Harris'],['Calvin Harris'],52.0
nO+tjL6/qHgNO/ui0TjeP+nSsD+aoGcT9AHU7Dtrzsc=,3,4,227327,['880'],['Casting Crowns'],"['Mark Hall', 'Matt Maher', 'John Mabe', 'Blak...","['Mark Hall', 'Matt Maher', 'John Mabe', 'Blak...",52.0
ZxB4Y6OFY7oArWVqRWofM3g714CWrHbY4ohABjzGLFE=,4,5,256052,['1609'],['Robin Schulz'],"['Dennis Bierbrodt', ' Guido Kramer', ' Robin ...","['Dennis Bierbrodt', ' Guido Kramer', ' Robin ...",52.0
...,...,...,...,...,...,...,...,...
EbqcQXfWAWmL2jUxdJOm7k+Jge6K4L2Zt0rPEAgKP+o=,96251,116860,225930,['465'],['Jennifer Lopez'],"['Jennifer Lopez', ' Karen Anderson', ' Mario ...","['Jennifer Lopez', ' Karen Anderson', ' Mario ...",52.0
rmXJokLQsxmlS9Vo6zd3Y3xEV0XgytHsG9D7ZENbuUs=,96377,117015,218759,['1259'],['Maître Gims'],"['Maître Gims', ' Renaud Rebillaud']","['Maître Gims', ' H-Magnum']",52.0
pYecPfmYfolqr6ZeqS8ZF1KCxxTV5ZsQe37UTugrlnY=,96394,117033,239165,['437'],['FETISH the WORLD'],['FETISH the WORLD'],['FETISH the WORLD'],17.0
qz+HYG3QYATLIqKQo5/eUafABJ/6UyATkHHOnClhHqY=,96540,117212,192156,['2022'],['Forget the G'],"['Eric M.Y. Chan', ' Wong Hin Ching', ' Chan K...",['Eric M.Y. Chan'],52.0
+vl0D7GrCQ5lMpWqAeLJ+Nc/E+tMkwL/6eyRjBouOd8=,96728,117437,236356,"['388', '873']",['John Owen-Jones'],['Alain Boublil'],"['Alain Boublil', ' Claude Michel Schonberg', ...",-1.0

In [12]:
songs=df1['song_id'].tolist()

In [13]:
print(len(dataframe))

105779

In [14]:
dataframe.head()

,Unnamed: 0,Unnamed: 0.1,msno,song_id,source_system_tab,source_screen_name,source_type,target
0,16,34,RPLdWVYe6joZEnv9TzljsdCWMtKopKpRXk1hKAnQQCQ=,K2jkXlozk/+HPjs1RyDlBUHJx2Ky+ITavwBXPcFqtHY=,my library,Local playlist more,local-library,0
1,61,167,LGIeu7rj6KryPWev2nr5g807ZPtw4b59wqDn5jighcw=,zHqZ07gn+YvF36FWzv9+y8KiCMhYhdAUS+vSIKY3UZY=,discover,Online playlist more,song-based-playlist,1
2,63,170,LGIeu7rj6KryPWev2nr5g807ZPtw4b59wqDn5jighcw=,IKMFuL0f5Y8c63Hg9BXkeNJjE0z8yf3gMt/tOxF4QNE=,discover,Online playlist more,song-based-playlist,1
3,64,171,LGIeu7rj6KryPWev2nr5g807ZPtw4b59wqDn5jighcw=,MtFK4NN8Kv1k/xPA3wb8SQaP/jWee52FAaC1s9NFsU4=,discover,Online playlist more,song-based-playlist,1
4,68,176,LGIeu7rj6KryPWev2nr5g807ZPtw4b59wqDn5jighcw=,9YYrODwrXpDcCjOJypHROv3f5z40y11QlmgQjmzp2vQ=,discover,Online playlist more,song-based-playlist,1

In [17]:
#takes a lot of time: run only if required, output already in 'cleaned_listofsongs_and_behavior_peruser.csv'
user_songs={}
for i in dataframe.index:
    if dataframe['msno'][i] not in users:
        continue
    if dataframe['song_id'][i] in songs:
        if dataframe['msno'][i] not in user_songs:
            user_songs[dataframe['msno'][i]]=[]
        user_songs[dataframe['msno'][i]].append((dataframe['song_id'][i],dataframe['source_system_tab'][i]))

In [18]:
dataframe.head()

,Unnamed: 0,Unnamed: 0.1,msno,song_id,source_system_tab,source_screen_name,source_type,target
0,16,34,RPLdWVYe6joZEnv9TzljsdCWMtKopKpRXk1hKAnQQCQ=,K2jkXlozk/+HPjs1RyDlBUHJx2Ky+ITavwBXPcFqtHY=,my library,Local playlist more,local-library,0
1,61,167,LGIeu7rj6KryPWev2nr5g807ZPtw4b59wqDn5jighcw=,zHqZ07gn+YvF36FWzv9+y8KiCMhYhdAUS+vSIKY3UZY=,discover,Online playlist more,song-based-playlist,1
2,63,170,LGIeu7rj6KryPWev2nr5g807ZPtw4b59wqDn5jighcw=,IKMFuL0f5Y8c63Hg9BXkeNJjE0z8yf3gMt/tOxF4QNE=,discover,Online playlist more,song-based-playlist,1
3,64,171,LGIeu7rj6KryPWev2nr5g807ZPtw4b59wqDn5jighcw=,MtFK4NN8Kv1k/xPA3wb8SQaP/jWee52FAaC1s9NFsU4=,discover,Online playlist more,song-based-playlist,1
4,68,176,LGIeu7rj6KryPWev2nr5g807ZPtw4b59wqDn5jighcw=,9YYrODwrXpDcCjOJypHROv3f5z40y11QlmgQjmzp2vQ=,discover,Online playlist more,song-based-playlist,1

In [20]:
print(user_songs)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [21]:
import csv

In [22]:
with open('user_song_behaviour_dict.csv', 'w') as csv_file:  
    writer = csv.writer(csv_file)
    for key, value in user_songs.items():
       writer.writerow([key, value])